# joshua stuckey 11/2/2012
# project Euler problem_1

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

counter = 0
i = 0
j = 1
k = 0
l = 0
while counter + k < 4000000
	k = i + j 
	j = i
	i = k
	counter += 1
	
	 if k % 2 == 0
     l = k + l
	 puts l
     end
end

# This one didnt take very long, get the fibonnaci calculated and then pull the even valued 
# terms and add them up. Found this interesting solution on the Euler Forums after i solved..
# pretty much the same as mine but with some different organization and syntax. Ill take a 
# look at the break if and the loop do when i get some time.
 
=begin
	
x=1
y=2
sum=0
loop do
   z=x+y
   if y%2==0
      sum+=y
   end
   x=y
   y=z
   break if y>=4000000
end
puts sum
	
end
=end